#!/bin/bash
for ui in $(find panels/*/*.ui)
do
  intltool-extract --type=gettext/glade $ui
done

xgettext --language=C --from-code=UTF-8 --keyword=_ --keyword=N_ --output=cinnamon-control-center.pot panels/*/*.c shell/*.c panels/*/*.ui.h generate_additional_files.py

rm -f panels/*/*.ui.h
